### ISSUE TITLE
Weird Polymer Catalog Bug (Md) -- "paper-toast"

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-element-catalog#101]
Dear Sirs,

It seems I found a bug in Polymer Catalog. To reproduce, please follow these steps:

1. Open polymer catalog: https://elements.polymer-project.org/
2. Choose Md (Paper Elements)
3. From paper elements select paper-button; switch to demo in left pane
4. Select "paper-toast" from "other elements"
5. Now, select any other element, e.g. "paper-menu" -- "paper-toast" disappears from elements catalog.

More weird behavior:

1. Repeat steps 1-4 above
2. Now, select "paper-toggle-button"
3. Now, again select "paper-toast" -- "paper-toggle-button" disappears!
4. You can toggle between "paper-toast" and "paper-toggle-button" by clicking "paper-toast" element.

Best regards!

**Comment by ebidel** [comment]
This issue is old and I don't think it's still reproducible. Please reopen if you see otherwise.
