### ISSUE TITLE
"undefined" sections of Element website on Windows Firefox

### ISSUE THREAD

**Issue by section14** [Polymer/polymer-element-catalog#102]
I'm getting "undefined" in the using elements section of the site while using Firefox on Windows (it just updated also). It's working fine in Chrome. I do have the adblocker extension installed, but it's disabled for this site.

Screenshot:

![polymer_page](https://cloud.githubusercontent.com/assets/1625835/7961530/1d315c02-09d6-11e5-9361-2de0241cbb2c.jpg)

**Comment by atotic** [comment]
Me too. Looks like marked-element is not marking.

**Comment by arthurevans** [comment]
@mbleigh Is this an issue with the site or should I be marking up code samples differently? I don't know the infrastructure well enough to guess.

**Comment by mbleigh** [comment]
Seems to be some kind of Firefox specific issue with `marked-element`. I'll investigate.
