### ISSUE TITLE
[Accessibility] Keyboard navigation issues on left panel

### ISSUE THREAD

**Issue by lpalmaro** [Polymer/polymer-element-catalog#105]
The left panel that appears is accessible with the screen reader, but not keyboard only. I need to be able to tab to this section of the page, then use the up/down arrows to cycle through the various items (and have a clear focus state), then press enter to activate.

Tested: 
Chrome OS / ChromeVox
Mac / VoiceOver
Win / NVDA

**Comment by mbleigh** [comment]
The left sidebar is now keyboard navigable using Tab/Alt+Tab since #121 was merged, however the tabindex orders aren't right at the moment.

**Comment by mbleigh** [comment]
This has been solved by other commits.
