### ISSUE TITLE
[Accessibility] Table accessibility

### ISSUE THREAD

**Issue by lpalmaro** [Polymer/polymer-element-catalog#106]
In list view, the icons for add to cart and view docs in the table currently just read "link" with VoiceOver. This is totally unhelpful for screen reader users. Please make sure these have sufficient alt text.

Tested: "Chrome OS / ChromeVox
Mac / VoiceOver
Win / NVDA"

**Comment by azakus** [comment]
#107 is very related to this. When adding keyboard nav for the table, just make sure whatever highlights the row works for mouse and keyboard.
