### ISSUE TITLE
[Accessibility] Table contrast and focus issues

### ISSUE THREAD

**Issue by lpalmaro** [Polymer/polymer-element-catalog#107]
The contrast on the icons in the right of the table is really poor. When I hover over these with my mouse, I can see that they become much darker, but this does not occur when using the keyboard only. Please make sure that as keyboard focus goes there, they become much darker the same way they do with the mouse hover. Otherwise, it’s impossible to see them.

**Comment by mbleigh** [comment]
Fixed by deeb00a
