### ISSUE TITLE
[Accessibility] Icon alt text confusion in left panel

### ISSUE THREAD

**Issue by lpalmaro** [Polymer/polymer-element-catalog#110]
On the left navigation panel, the icons for Md, Fe, Go, etc. are a bit confusing with a screen reader. As I navigate through, I hear, for example "Md", then press next, then hear "paper elements". I don't have a clear concept that these two are on the same line and are actually the same thing. Maybe we could just make sure that the icons are images, so the screen reader will read "Md, image" to be more clear.

Tested: "Chrome OS / ChromeVox
Mac / VoiceOver
Win / NVDA

**Comment by azakus** [comment]
We should probably just `aria-hidden` the product icons, or set an explicit `aria-label` on the item to be the full name.
