### ISSUE TITLE
npm run serve doesn't seem to work as described in the readme

### ISSUE THREAD

**Issue by kbwatts** [Polymer/polymer-element-catalog#111]
I might be missing something obvious, but from simply following the Getting Started steps, all is well until `npm run serve` which doesn't throw any errors (see screenshot), but also doesn't actually start the local server with all the gulp awesomeness, as `gulp serve` alone does in the Polymer Starter Kit (see 2nd screenshot).

Currently:
![screen shot 2015-06-06 at 10 11 25 am](https://cloud.githubusercontent.com/assets/961706/8017269/c26036ca-0c34-11e5-81c0-3ee8e4b92cb5.png)

Expected:
![screen shot 2015-06-06 at 10 15 52 am](https://cloud.githubusercontent.com/assets/961706/8017286/205a6458-0c35-11e5-8f0a-a1ef856a5a98.png)

**Comment by mbleigh** [comment]
This was a dependency issue that should be working now with a fresh npm install and bower update

**Comment by kbwatts** [comment]
Works! thanks @mbleigh :+1:

**Comment by mcarey1590** [comment]
I am experiencing this same issue on the latest release 1.0.11

**Comment by mcarey1590** [comment]
I am experiencing this same issue with the latest version. It will list all the elements and then hang until terminated.
