### ISSUE TITLE
Neon-animation demo link isn't showing up

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer-element-catalog#113]
It shows up on the table view, and points to the right [demo](https://elements.polymer-project.org/elements/neon-animation?active=fade-in-animation&view=demo:demo/index.html):
![screen shot 2015-06-08 at 12 18 31 pm](https://cloud.githubusercontent.com/assets/1369170/8043104/7fbd0a96-0dd8-11e5-87f0-51690879afa9.png)

But it does not appear on the docs page anywhere no matter what element/behavior is selected:

![screen shot 2015-06-08 at 12 17 45 pm](https://cloud.githubusercontent.com/assets/1369170/8043094/6c5082ee-0dd8-11e5-8aa9-1d0b88bfd644.png)

/cc @morethanreal

**Comment by arthurevans** [comment]
Possibly related to #96 , #77?

**Comment by frankiefu** [comment]
Needs to be fixed in neon-animation's bower.json
