### ISSUE TITLE
review usage of the phrase "Google's Web Components"

### ISSUE THREAD

**Issue by sjmiles** [Polymer/polymer-element-catalog#117]
It's used both on this repo description, and in the meta-tag of the index page:

`<meta name="description" content="A catalog of Google's Web Components">`

I suspect another designation is preferred.

**Comment by addyosmani** [comment]
Suggestions:

* A catalog of elements for Google's APIs
* A catalog of elements for Google services

**Comment by sjmiles** [comment]
@addyosmani: note that this phrasing today is attached to the general catalog, not specifically for the elements related to Google APIs or services.

**Comment by addyosmani** [comment]
Ah, I see. Please ignore my comment. I was under the impression this was specific to the phrasing for that collection.

**Comment by tjsavage** [comment]
Yes good catch, this was a holdover from the old branding. Updated!
