### ISSUE TITLE
On Safari/Firefox, clicking on any element on the elements page does nothing

### ISSUE THREAD

**Issue by frankiefu** [Polymer/polymer-element-catalog#123]
On Safari, open: https://elements.polymer-project.org/browse?package=paper-elements
Now try to click on any element, e.g. paper-input and nothing happens.

**Comment by frankiefu** [comment]
Looks like a regression from this commit: https://github.com/Polymer/polymer-element-catalog/commit/5e0fcc48692ffe73bf4eef936f63e593de25f861

**Comment by mbleigh** [comment]
Yeah, it's a regression -- I don't have a Mac but it's likely caused by my wrapping the `package-tile` elements in an `<a>` tag. If someone who does have a Mac can investigate that'd be great.

**Comment by frankiefu** [comment]
Can also reproduce it on Firefox too.

**Comment by frankiefu** [comment]
In https://github.com/Polymer/polymer-element-catalog/blob/5e0fcc48692ffe73bf4eef936f63e593de25f861/app/elements/element-table/element-table.html#L145, 
event.path is only supported in Chrome and we can't use that there.
