### ISSUE TITLE
paper-responsive-change event name cut off in documentation

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer-element-catalog#127]
Moved from https://github.com/PolymerElements/paper-drawer-panel/issues/64

In the [documentation page for `paper-drawer-panel`](https://elements.polymer-project.org/elements/paper-drawer-panel), the name of the `paper-responsive-change` event title is cut off, and appears to be `paper-responsive-`.  

I believe this is because the description of the event does not flow onto multiple lines.  Note the top of the "h" is peaking out from the next line.

![screen shot 2015-06-14 at 10 16 29 pm](https://cloud.githubusercontent.com/assets/2433509/8153504/913ee504-12e3-11e5-844d-426fa4906fce.png)

**Comment by ebidel** [comment]
Looks fixed:

<img width="516" alt="screen shot 2015-10-04 at 9 41 28 am" src="https://cloud.githubusercontent.com/assets/238208/10268930/1efbca20-6a7c-11e5-800f-3f9f26428d9b.png">
