### ISSUE TITLE
documentation bug; search elements

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer-element-catalog#129]
_From @dsaronin on June 13, 2015 0:24_

Typing in "paper-drawer-toggle" in the search bar of the Polymer Elements page (screenshot) in order to view all element docs referencing the search phrase fails to turn up anything, yielding the following: 
```
'paper-drawer-toggle' Elements 0
```

It would be nice to actually be able to search through all the polymer documents for a particular result or reference. I hear that a young company out of Mountain View has a search engine with exceptional capability; "Google" I think is their name.

![screenshot from 2015-06-12 17 18 51](https://cloud.githubusercontent.com/assets/410380/8142108/babc9524-1127-11e5-9d4e-3b85940fc1a1.png)

_Copied from original issue: Polymer/polymer#1858_

**Comment by arthurevans** [comment]
_From @sorvell on June 15, 2015 17:52_

Should be posted in https://github.com/Polymer/polymer-element-catalog/issues.

**Comment by blasten** [comment]
This issue seems to have been fixed.

**Comment by arthurevans** [comment]
I don't think this is actually fixed in the general case. `paper-drawer-panel` now shows up for some reason, but search is still mostly broken. However, requirements are better captured in #165.
