### ISSUE TITLE
don't allow unclick of download options

### ISSUE THREAD

**Issue by drewpca** [Polymer/polymer-element-catalog#134]
![image](https://cloud.githubusercontent.com/assets/5224714/8193178/1d128582-1428-11e5-9e07-cd6ef83ed9ea.png)
If I click that selected radio button, it turns off. Clicking the selected one should be a no-op. Hopefully the API (or docs) can be changed so other developers don't make this mistake too. It ought to be really hard and explicit to make radio buttons behave like anything other than <input type="radio"> elements.

Seems related to https://github.com/PolymerElements/paper-radio-button/issues/27

**Comment by notwaldorf** [comment]
I think this should be fixed once the catalog pulls the latest version of `paper-radio-group`

**Comment by mbleigh** [comment]
Confirmed that this is fixed by updated paper-radio-group. Closing issue, will go live with next deploy.
