### ISSUE TITLE
extra comma after tag list

### ISSUE THREAD

**Issue by drewp** [Polymer/polymer-element-catalog#136]
https://elements.polymer-project.org/browse?package=iron-elements first row says "a11y , live ," for the tags. Sometimes the comma wraps into a new row.

**Comment by Scarygami** [comment]
I already sent a PR to fix this a few days ago, but it seems no-one is looking at the PRs in this repo... https://github.com/Polymer/polymer-element-catalog/pull/132

**Comment by frankiefu** [comment]
fixed by https://github.com/Polymer/polymer-element-catalog/pull/132
