### ISSUE TITLE
https://elements.polymer-project.org/elements/iron-media-query

### ISSUE THREAD

**Issue by samuelcardillo** [Polymer/polymer-element-catalog#139]
The documentation is giving the attribute "queryMatches" 
```html 
<iron-media-query query="(min-width: 600px)" queryMatches="{{queryMatches}}"></iron-media-query>
```

which is not working as the good attribute is "query-matches" 
```html 
<iron-media-query query="(min-width: 600px)" query-matches="{{queryMatches}}"></iron-media-query>
```

**Comment by tjsavage** [comment]
This issue was moved to PolymerElements/iron-media-query#13

**Comment by tjsavage** [comment]
Thanks! This needs to be fixed - moved to `iron-media-query` as that's where the docs reside
