### ISSUE TITLE
Demos not shown in element catalog

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-element-catalog#140]
_From @oathcomrade on June 19, 2015 20:25_

If I select any element in the element catalog and click on _Demo_, nothing is shown. Refreshing the page doesn't help.
The console shows this warning:
[page-element::_annotatedComputationEffect]: compute method `baseURI` not defined

_Copied from original issue: Polymer/polymer#1923_

**Comment by tjsavage** [comment]
_From @kevinpschaaf on June 22, 2015 20:36_

This issue tracker is for the core Polymer library.  We'll get this moved to the https://github.com/Polymer/polymer-element-catalog/issues tracker.

**Comment by Zelgod** [comment]
Upgrading chrome from 41.0.2272.101-1 to 43.0.2357.130-1 resolved this for me (Ubuntu).

**Comment by DmitryAuine** [comment]
+1 ubuntu chrome

**Comment by DmitryAuine** [comment]
@tjsavage

**Comment by ebidel** [comment]
This issue has gone stale. If you still are seeing issues, please reopen.

**Comment by olivier-derpierre** [comment]
Looks like it's caused by older versions of chrome not liking you overriding the baseURI method on an element in page-element.html. Renaming the property to _baseURI fixes the problem on chrome 34.
