### ISSUE TITLE
Bug while typing in search bar

### ISSUE THREAD

**Issue by fxedel** [Polymer/polymer-element-catalog#147]
When I type a letter in the search bar at the main page, it instantly shows the result. The new search bar in the navigation already has the focus, but the cursor is at the first and not at the last position.

When I search for example for "paper", I type in the "p", the cursor is at the first position, I type in the "aper" and my final search query is "aperp".

That's really annoying. Is it possible to set the cursor position with JS? I used the latest Firefox version ...

**Comment by samccone** [comment]
:white_check_mark: verified to be firefox specific

**Comment by fxedel** [comment]
:+1: :+1: :+1:
