### ISSUE TITLE
Datepicker element?

### ISSUE THREAD

**Issue by oswaldomilet** [Polymer/polymer-element-catalog#148]
I would like to make a suggestion to Polymer Team give us a datepicker element (with internationalization support). It's a very usefull and required in lots of apps. Angular team is building one in [Angular Material](https://t.co/ID6A2aRM7l). Tks

**Comment by notwaldorf** [comment]
It's on the elements request list. You can keep an eye on https://github.com/Polymer/paper-elements/issues/20#issuecomment-112939552 for updates on the 1.0 date picker. :)

**Comment by oswaldomilet** [comment]
Thanks
