### ISSUE TITLE
No documents for iron-flex-layout

### ISSUE THREAD

**Issue by jmuk** [Polymer/polymer-element-catalog#149]
iron-flex-layout could be a key element for those who wants to migrate from Polymer 0.5.x (or those who are familiar with it), but it has no documents nor demos in the catalog.
https://elements.polymer-project.org/elements/iron-flex-layout

It's described in the migration guide as https://www.polymer-project.org/1.0/docs/migration.html#layout-attributes

**Comment by ebidel** [comment]
Fixed.
