### ISSUE TITLE
Missing documentation for iron-icons

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-element-catalog#151]
_From @adrifelt on July 9, 2015 16:23_

There's no information about iron-icons in the element catalog for polymer 1.0. In contrast, 0.5 documentation has a great page with examples of all the different icons.

<img width="1325" alt="screen shot 2015-07-09 at 6 18 08 am" src="https://cloud.githubusercontent.com/assets/4962198/8600674/d68ac240-2602-11e5-91ea-6a1f8f868586.png">

_Copied from original issue: Polymer/polymer#2055_

**Comment by tjsavage** [comment]
_From @kevinpschaaf on July 9, 2015 16:50_

This issue tracker is for the core Polymer library, not elements created with it.  We'll move this issue to the correct tracker.

**Comment by Compufreak345** [comment]
I might add that in the iron overview page the non-existing doc is linked, but the demo containing all icons is not. It is available, but not linked : https://elements.polymer-project.org/elements/iron-icons?active=iron-icons&view=demo:demo/index.html

**Comment by ebidel** [comment]
This has been long fixed: https://elements.polymer-project.org/elements/iron-icons
