### ISSUE TITLE
Feature request: Put github repo link for each element in catalog for that element

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer-element-catalog#158]
_From @dman777 on July 25, 2015 2:27_

Feature request: Put github repo link for each element in the catalog for that element. This would be beneficial because the the github code contains demos and examples that the catalog does not. I almost always refer to the code so it would be a great convenience rather than googling. 

_Copied from original issue: Polymer/polymer#2150_

**Comment by samccone** [comment]
I think this was resolved with this pr :ice_cream: 
https://github.com/Polymer/polymer-element-catalog/pull/153

**Comment by samccone** [comment]
friendly ping :walking:
