### ISSUE TITLE
Service worker demo fails / doesn't degrade gracefully in Safari

### ISSUE THREAD

**Issue by thomasrhiel** [Polymer/polymer-element-catalog#161]
The [platinum-sw service worker demo](https://elements.polymer-project.org/elements/platinum-sw?view=demo:demo/index.html&active=platinum-sw-cache) isn't working in Safari (desktop or mobile). Selecting an ebook does nothing. The demo's text intro suggests it should work when connected to the network: 

>browsers that lack service worker support will still have a functional (online-only) eBook reader

**Comment by thomasrhiel** [comment]
(Edited to remove references to FF. My mistake. It's working just fine there.)

**Comment by samccone** [comment]
I wonder if this should be an issue filed in the platinum-sw repo.

What do you think @thomasrhiel ?

**Comment by thomasrhiel** [comment]
Yep, this appears to be a dupe of https://github.com/PolymerElements/platinum-sw/issues/10
