### ISSUE TITLE
polymer-project.org Element catalog - downloading individual elements error

### ISSUE THREAD

**Issue by tjsavage** [Polymer/polymer-element-catalog#168]
_From @pippintook on August 19, 2015 21:8_

After selecting the  "elements folder" method and then clicking download, I get this error message -
![screenshot 2015-08-20 at 07 06 32](https://cloud.githubusercontent.com/assets/11688445/9369051/2dd8c420-470a-11e5-919f-790f96138925.png)
I'm on the latest Chrome OS dev channel.

_Copied from original issue: Polymer/polymer#2317_

**Comment by ebidel** [comment]
Are you still seeing this? This would probably come from the bower zipper, but the mimetype is being set properly on the server (https://github.com/PolymerLabs/bowerzipper/blob/master/zipper/server.js#L119). Not sure why it's coming back an an .html file though.

**Comment by pippintook** [comment]
Actually, yeah, I am. I've tested it on a Windows machine on the same network and it works fine - maybe it's something to do with the way Chrome OS is handling the download?

**Comment by ebidel** [comment]
Yea not sure. It has the correct mimetype so no idea why Chrome OS would go bonkers. `bower install` is always recommended :)

**Comment by ebidel** [comment]
I'm going to close this, as we haven't had other user reports and there's not much we can do if the OS isn't treating .zip downloads correctly. It's possible you have a chrome extension interfering as well.

**Comment by pippintook** [comment]
Okay, thanks for looking into it. (Loved your Polymer Summit talk! :)

**Comment by ebidel** [comment]
Thanks!
