### ISSUE TITLE
Guides try to load themselves

### ISSUE THREAD

**Issue by arthurevans** [Polymer/polymer-element-catalog#176]
_From @gertcuykens on September 10, 2015 20:29_

Stuck in a javascript infinite loop (chrome)

https://elements.polymer-project.org/guides/flex-layout

_Copied from original issue: Polymer/docs#1348_

**Comment by arthurevans** [comment]
_From @gertcuykens on September 10, 2015 20:33_

Thats weird, it apparently sometimes get stuck, not always??? Do you see the flash the first halve a second too?

**Comment by arthurevans** [comment]
I haven't seen it get stuck in a loop, but I have seen a flash of weird content. @frankiefu it looks like the content's loading twice, like there's a race between two code paths that are both reacting to the URL change (or page load).

**Comment by ebidel** [comment]
I also dont see an infinite loop, but I do see the guide try to briefly load itself.

**Comment by frankiefu** [comment]
We did some perf improvements in the router (https://github.com/Polymer/polymer-element-catalog/pull/188) and that seems to help fix this issue.
