### ISSUE TITLE
404 invalid element pages

### ISSUE THREAD

**Issue by samccone** [Polymer/polymer-element-catalog#178]
vist:

https://elements.polymer-project.org/elements/%F0%9F%90%83%F0%9F%90%83%F0%9F%90%83%F0%9F%90%83?active=null

![screen shot 2015-09-18 at 10 04 46 am](https://cloud.githubusercontent.com/assets/883126/9965696/b569a83e-5dec-11e5-9f95-3e9a8dee3280.png)

**Comment by arthurevans** [comment]
Dude, in order to be a valid custom element name, it needs to include a hyphen, like: 🐃-🐃🐃🐃. See, I fixed that for you. :D

**Comment by samccone** [comment]
:boar:

**Comment by blasten** [comment]
This issue should be fixed now!

**Comment by arthurevans** [comment]
Is the fix deployed? I'm still seeing a "No documentation found" page for "paper-badger".

Badgers? We don't need no stinkin' badgers!
