### ISSUE TITLE
Demo does not open in IE11

### ISSUE THREAD

**Issue by sbley** [Polymer/polymer-element-catalog#196]
At https://elements.polymer-project.org, if you click on "demo" using IE11 then nothing happens. The demo doesn't open.
![demo](https://cloud.githubusercontent.com/assets/686538/10542105/16facd78-7416-11e5-9e74-8ae495ead7fb.png)
The following javascript error is logged:
![clipboard03](https://cloud.githubusercontent.com/assets/686538/10542144/61f5b176-7416-11e5-99c0-bd6b6f5e98ba.png) which translates "method find() not supported"

**Comment by frankiefu** [comment]
This is a regression from https://github.com/Polymer/polymer-element-catalog/commit/0326093fe68c1da4a3885551ef74a8df5c1592f9

**Comment by blasten** [comment]
This issue is fixed now
