### ISSUE TITLE
Analytics pageview on /guides is no longer being recorded after router update

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer-element-catalog#197]
On page load, GA is loaded just fine. But I suspect it's b/c of the [router change](https://github.com/Polymer/polymer-element-catalog/commit/0326093fe68c1da4a3885551ef74a8df5c1592f9) that no longer creates new pages as you navigate.

Repo:
1. Goto https://elements.polymer-project.org/guides/
2. Click to other guides

Network panel only shows one request for the `collect` endpoint.

<img width="398" alt="screen shot 2015-10-19 at 11 37 41 am" src="https://cloud.githubusercontent.com/assets/238208/10587506/2e654c8a-7656-11e5-81e4-1700498bf784.png">

:(

**Comment by blasten** [comment]
We removed a few infinite async loops. :'(
