### ISSUE TITLE
Eliminate needless jargon is the element catalog

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer-element-catalog#201]
_From @CSEMike on October 23, 2015 18:49_

The Polymer element catalog is extremely useful. It's my first stop when searching for how to express my UI using Polymer elements.
  https://elements.polymer-project.org/browse?package=platinum-elements

A frustration, however, is navigating the top-level jargon. What's a Gold element, and why is it different than a Neon element? Is the element I'm looking for a Molecule, or an... Iron something?

I know there's some internal theory as to why these have different names, but as a user, the need to internalize Polymer jargon to understand the difference seems needless.

I'm writing to request a flat list that is presented without jargon. I would like to use command-F in my browser to search for keywords like 'popup'. This would greatly accelerate my use of the Polymer docs and would be much appreciated.

_Copied from original issue: Polymer/polymer#2615_

**Comment by ebidel** [comment]
Improved search across the catalog (e.g. not just element names) will help: https://github.com/Polymer/polymer-element-catalog/issues/165

**Comment by CSEMike** [comment]
Broadly improved search is a fine goal, but I'm afraid we might be missing a very simple incremental improvement that solves the immediate problem. Concretely, Control-F in the browser offers excellent search functionality :)

**Comment by ebidel** [comment]
Ctrl-F is nice. Can't you already do that on https://elements.polymer-project.org/browse? There's still the question of being able to search element metadata.

**Comment by arthurevans** [comment]
The other problem with the browse view is that it really only shows package names, not element names. For example, it shows "neon-animation", but not "neon-animated-pages" or "paper-input-container".

**Comment by CSEMike** [comment]
Ah yes, /browse seems to be what I want for cmd-F. I'd say just drop all the category noise on the left.

Feel free to close.
