### ISSUE TITLE
Scrolling in element catalog not functioning.

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer-element-catalog#204]
_From @arcio on October 23, 2015 22:1_

I'm working in chrome Version 46.0.2490.71 (64-bit)
When viewing the catalog the left-hand column won't scroll.

For instance:
https://elements.polymer-project.org/elements/neon-animation

The page will scroll but the left column will not. You have to zoom out to be able to see the entire list.

_Copied from original issue: Polymer/polymer#2620_

**Comment by ebidel** [comment]
_From @abdonrd on October 24, 2015 9:25_

I confirm the problem.

**Comment by ebidel** [comment]
Easy fix is to add this to the `:host` rule in app-sidebar:

    overflow-y: auto;
    -webkit-overflow-scrolling: touch;

**Comment by frankiefu** [comment]
Seems like a regression from this commit: https://github.com/Polymer/polymer-element-catalog/commit/0326093fe68c1da4a3885551ef74a8df5c1592f9.  @blasten, we probably need to add back the `overflow-y: auto` in to the right place.

**Comment by blasten** [comment]
That's right, I can fix this one
