### ISSUE TITLE
Ripples are really pale

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer-element-catalog#209]
Go to https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html&active=paper-checkbox. Either click on a checkbox, or tab to a checkbox. If you click on it, the ripple is almost invisible. If you tab to a checkbox, the very pale ripple flashes, but doesn't stay displayed. This doesn't happen if you run the demo locally.

**Comment by blasten** [comment]
This is a bug in Chrome & it's hard to reproduce without all this context. I debugged it and found that if you add display:none or opacity: 0.99 to this input, the issue goes away.
<img width="267" alt="input" src="https://cloud.githubusercontent.com/assets/1410613/10916650/4b2e6baa-8211-11e5-8c8c-c4958a652493.png">
@frankiefu wdyt? should we go with that fix?

**Comment by frankiefu** [comment]
adding `opacity: 0.99` to input doesn't fix it for me.
