### ISSUE TITLE
Catalog is showing `observers` array as part of public api :(

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer-element-catalog#210]
Not sure if this is due to a recent deployment.

<img width="538" alt="screen shot 2015-11-03 at 5 50 22 pm" src="https://cloud.githubusercontent.com/assets/238208/10927304/7ee8ee60-8253-11e5-93a8-000a3df8efbd.png">

**Comment by blasten** [comment]
@garlicnation I found that hydrolysis doesn't set `configuration:true` there. Would you mind taking a look?

**Comment by garlicnation** [comment]
The problem is that I'm not special-casing `observers` in a behavior. I can fix it in the next couple of days.

**Comment by blasten** [comment]
friendly ping @garlicnation

**Comment by garlicnation** [comment]
Should be resolved by https://github.com/Polymer/hydrolysis/pull/197
