### ISSUE TITLE
paper-dropdown-menu demo includes elements.build.html, which breaks it

### ISSUE THREAD

**Issue by rictic** [Polymer/polymer-element-catalog#213]
URL: https://elements.polymer-project.org/bower_components/paper-dropdown-menu/demo/index.html

I poked around in the inspector for a while but I couldn't see any files that were referencing `elements.build.html`, but something is. This causes a bunch of problems, not the least of which is that the polymer js gets run twice, causing all sorts of chaos.

**Comment by blasten** [comment]
Routes are delegated to index.html if the file in the URL isn't found in the server's file system. In this case, `paper-listbox` hasn't been included in paper-elements.html, so that request is going through index.html.
