### ISSUE TITLE
The demo is not visible in the elements catalog

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer-element-catalog#243]
_From @zoechi on November 27, 2015 7:17_

https://elements.polymer-project.org/elements/gold-cc-cvc-input

_Copied from original issue: PolymerElements/gold-cc-cvc-input#33_

**Comment by notwaldorf** [comment]
Ah, good catch. Il'll take a look. Here's what the demo should point to, in the meantime: https://elements.polymer-project.org/elements/gold-cc-cvc-input?view=demo:demo/index.html&active=gold-cc-cvc-input

**Comment by notwaldorf** [comment]
Going to move this to the polymer-elements-catalog, since this element seems to be doing everything fine (it has an annotation, the `bower.json` looks right)

**Comment by arthurevans** [comment]
This issue was moved to PolymerElements/gold-cc-cvc-input#38
