### ISSUE TITLE
chrome issue

### ISSUE THREAD

**Issue by Geoffrey-Pliez** [Polymer/polymer-element-catalog#269]
Hi,
I have an empty page with Chrome and Chrome Canary with this message :

polydev/vendor/zone-microtask.js:973           Uncaught TypeError: Cannot read property 'toString' of null

but I have no problem with Edge and Firefox.

**Comment by tao-guo** [comment]
Same here. It used to be working.
```
local@ltp-xxx:~$ chromium-browser --version
Chromium 50.0.2661.102 Ubuntu 14.04
```

shop demo is OK.

**Comment by ebidel** [comment]
Please disable the polydev extension.
