### ISSUE TITLE
The cart sidebar hides when trying to copy the bower command

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-element-catalog#54]
This prevents copying the command.

**Comment by notwaldorf** [comment]
On mobile this is even worse -- the sidebar is longer than the screen size, so you try to scroll, which makes it go away. Understandably, downloading on mobile is a little weird, but the copying part is pretty big (@justinfagnani can decrease the priority if he wants)

**Comment by mbleigh** [comment]
@tjsavage should the cart just generally be hidden away on mobile-size screens? Seems like there isn't much use case for the cart on a smart-phone.

**Comment by frankiefu** [comment]
Related to https://github.com/PolymerElements/paper-drawer-panel/issues/50

**Comment by tjsavage** [comment]
Agreed that there's no use-case for the cart on mobile, but I dislike removing functionality since it's hard to say what "mobile" means anymore. I'd like to see if we can find a way to keep the cart as a drawer.
