### ISSUE TITLE
Excluding the current element from the list in the nav bar is confusing

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-element-catalog#56]
I selected paper-behavior from the list of "other elements" and was surprised to see it removed from the list.

Changing the list makes it hard to navigate by clicking down the list, because sometimes you don't move you cursor to select the next element and sometimes you do.

**Comment by notwaldorf** [comment]
I would vote for `All Elements` with a highlight as well. I tried to click linearly on all the elements, but because they kept disappearing, I ended up clicking on the first item several times until I figured it out. :)

**Comment by tjsavage** [comment]
Agreed - I think best behavior would be to keep the list static with the currently selected one highlighted.
