### ISSUE TITLE
"No documentation found" page leaves artifacts from previously viewed element

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-element-catalog#57]
Example from paper-styles
![screen shot 2015-05-26 at 12 18 07 pm](https://cloud.githubusercontent.com/assets/522948/7821106/613c9c3a-03a1-11e5-8434-1a1bf85c7900.png)

**Comment by mbleigh** [comment]
Moved to PolymerElements/iron-component-page#27
