### ISSUE TITLE
Element pages should have an Installation section

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer-element-catalog#58]
As an alternative to adding to cart and then downloading a bower.json, I'd like to just see the dependency line that I can copy and paste into my existing bower.json. A `bower install` command line would be nice too.

**Comment by rohanray** [comment]
+1

**Comment by ahomu** [comment]
:+1:

**Comment by pocotan001** [comment]
+1

**Comment by ebidel** [comment]
+1

**Comment by robdodson** [comment]
Yeah the first box on an element's page should be

## Installation

```
bower install --save PolymerElements/[some-element-name]
```

**Comment by ebidel** [comment]
Long fixed
