### ISSUE TITLE
Demo links bounce back to docs

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer-element-catalog#62]
Clicking on the <eye> demo link from a product line list goes to a demo URL, then immediately bounces back to the docs link

1. https://elements.polymer-project.org/browse?package=paper-elements
2. Click on <eye>
3. No demo

**Comment by mbleigh** [comment]
This is a binding/timing issue where a selector isn't populated with the demos yet so defaults thereby changing the value and reverting to docs.

Need to write some logic to wait until element is fully loaded and demo still is shown not to exist before reverting view to docs.

**Comment by kevinpschaaf** [comment]
Fixed `iron-component-page` to allow setting a demo from outside here:
https://github.com/PolymerElements/iron-component-page/pull/24

Remaining issue is to add the default demo URL to catalog.json, and use that as the view here:
https://github.com/Polymer/polymer-element-catalog/blob/master/app/elements/element-action-menu/element-action-menu.html#L29

**Comment by sorvell** [comment]
Should be fixed via: https://github.com/PolymerElements/iron-component-page/commit/e8887c1c9c1828b318b038e33d52593186b9c55f. Just need a release for iron-component-page.

**Comment by sorvell** [comment]
Fixed via https://github.com/PolymerElements/iron-component-page/commit/1f0cc2cafea23d2712db695a5d6e694ab816a4d7
