### ISSUE TITLE
Ripples are almost invisible in the demos.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer-element-catalog#66]
I recently came across with an issue that I'm not sure if it's a Chrome bug or related to the css in the catalog.
I you go to https://elements.polymer-project.org/elements/paper-checkbox?view=demo:demo/index.html you will notice that when you tap on a checkbox the ripple is very light, almost invisible.  If you open the demo separately, the ripple is back: https://elements.polymer-project.org/bower_components/paper-checkbox/demo/index.html

I was trying to debug it, but I couldn't find anything. To my surprise, if you are in the catalog and you resize the window, you will notice that the ripple starts to work once the left side panel disappeared.  It works fine in Firefox and Safari though.  It's only in Chrome.

cc @cdata @notwaldorf @morethanreal

**Comment by notwaldorf** [comment]
Bumping the p1 since this is pretty bad for demonstrating that elements are accessible.

**Comment by frankiefu** [comment]
Looks like this is an issue in `paper-drawer-panel` https://github.com/PolymerElements/paper-drawer-panel/issues/51

**Comment by blasten** [comment]
fixed now.
