### ISSUE TITLE
Fails to show any elements in IE11

### ISSUE THREAD

**Issue by IntranetFactory** [Polymer/polymer-element-catalog#67]
![2015-05-28_1645](https://cloud.githubusercontent.com/assets/7462342/7870703/079ccc5e-0559-11e5-9be8-031652a32b43.png)

**Comment by mbleigh** [comment]
This is due to IE's inability to have `dom-repeat` templates inside of tables. We will fix this by sniffing for IE (gross, but necessary) and forcing card view if detected.
