### ISSUE TITLE
Doc links to behaviors are broken

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer-element-catalog#70]
Get this message, for example, in the console:

`Could not navigate to  Polymer.IronMenuBehavior`

**Comment by sjmiles** [comment]
Fwiw, it _seems_ like this only occurs when the behavior lives in a different package.

**Comment by mbleigh** [comment]
This isn't broken so much as it was never implemented. I believe that `iron-component-page` emits an event that can be listened for when a behavior is clicked.

The wrinkle that makes this not quite trivial is that currently we don't have catalog-wide metadata for what behaviors (or elements) are in what packages. This is relatively easy to surface and I think should be added to the `catalog.json` during the build step.

**Comment by sorvell** [comment]
@garlicnation We think this might be a hydrolysis problem. Can you take a look?

**Comment by sorvell** [comment]
e.g. Go to `paper-button` and click the link at the bottom to `PaperButtonBehavior`

**Comment by mbleigh** [comment]
Mitigated somewhat by 5a94714 but needs investigation as to why PaperButtonBehavior isn't getting picked up by hydrolysis during the build step.

**Comment by mbleigh** [comment]
Fixed upstream (for Firefox issue) in https://github.com/PolymerElements/iron-doc-viewer/commit/d800208b291637b3e6c9e845b4cbe2caa66f5e17 -- will be fixed live next time a release is cut.
