### ISSUE TITLE
mobile Safari: Touch scroll on elements page will cause the element to be selected

### ISSUE THREAD

**Issue by frankiefu** [Polymer/polymer-element-catalog#74]

**Comment by frankiefu** [comment]
The following fixes should address this issue.
https://github.com/Polymer/polymer/commit/bdf191b80b7abd812bcd93ab2c211ec866182144
https://github.com/PolymerElements/iron-selector/pull/23

**Comment by sorvell** [comment]
Just need polymer tagged to fix this...

**Comment by azakus** [comment]
Fixed with 1.0.1
