### ISSUE TITLE
Tap sometimes registered twice on mobile

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer-element-catalog#75]
Start on the home page, scroll down a bit, and tap paper elements. Sometimes it looks like there's a 2nd ghost tap and you're taken past the elements list and right to a specific element.

**Comment by sorvell** [comment]
It looks like this can also happen on IOS. If you tap on the grid/card layout when browsing an element package, it can switch and then switch back quickly.

**Comment by azakus** [comment]
I can't replicate in either the device mode of the Chrome dev tools, nor on a motox with chrome 43.

**Comment by azakus** [comment]
Also can't replicate in ios simulator

**Comment by azakus** [comment]
I think this was fixed with https://github.com/PolymerElements/iron-selector/commit/a04295434b491c3b3687ca33e474920a4b9624d3 (tagged as 1.0.2). If I downgrade to iron-selector 1.0.1, then I can replicate this, but it seems solved with 1.0.2.

**Comment by sorvell** [comment]
Happening pretty consistently on Nexus 5 now. The table/grid button has been removed, but just going from front page to an element group often goes directly to an element.

**Comment by sorvell** [comment]
ok, not seeing this anymore on `https://p-catalog-staging.firebaseapp.com`
