### ISSUE TITLE
Some elements docs are missing from a repository with multiple elements

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer-element-catalog#77]
For example, `paper-input` is missing the `paper-input` element. It looks like in the generated `paper-input.json`, `elements` is missing the element but `elementsByTagName` has the correct list of all elements.

**Comment by atomikolex** [comment]
Same with firebase-element, only firebase-collection gets drawn in.

**Comment by frankiefu** [comment]
Should be fixed now
