### ISSUE TITLE
Bad wrapping/overflow in docs

### ISSUE THREAD

**Issue by sqrrrl** [Polymer/polymer-element-catalog#86]
Found at least one instance where the API docs render poorly with long property or event names:

https://elements.polymer-project.org/elements/paper-slider

![paper-slider_-_polymer_element_catalog](https://cloud.githubusercontent.com/assets/346343/7893928/f7b194fe-0617-11e5-8bc6-e9f5909fca38.png)

**Comment by tjsavage** [comment]
auto-moving this issue to PolymerElements/iron-doc-viewer#45 and closing this one

**Comment by tjsavage** [comment]
Thanks for this! The documentation should be rendered via PolymerElements/iron-doc-viewer, so moved this to there.
