### ISSUE TITLE
Element catalog, google-analytics, docs missing

### ISSUE THREAD

**Issue by ebidel** [Polymer/polymer-element-catalog#88]
_From @cfjedimaster on May 30, 2015 13:40_

Title says it all.

_Copied from original issue: Polymer/polymer#1681_

**Comment by ebidel** [comment]
I'm seeing docs at https://elements.polymer-project.org/elements/google-analytics?active=google-analytics-query. @cfjedimaster can you be more specific.

**Comment by cfjedimaster** [comment]
Ugh, I apologize. It was my darn Chrome ad blocker extension. I need to
just kill it off as it keeps blocking things like this that I don't expect.
Sorry - please close.

On Sat, May 30, 2015 at 9:07 PM, Eric Bidelman <notifications@github.com>
wrote:

> I'm seeing docs at
> https://elements.polymer-project.org/elements/google-analytics?active=google-analytics-query.
> @cfjedimaster <https://github.com/cfjedimaster> can you be more specific.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Polymer/polymer-element-catalog/issues/88#issuecomment-107110510>
> .
>



-- 
===========================================================================
Raymond Camden, Developer Advocate for MobileFirst at IBM

Email : raymondcamden@gmail.com
Blog : www.raymondcamden.com
Twitter: raymondcamden
