### ISSUE TITLE
Github link to element repo in element catalog

### ISSUE THREAD

**Issue by Bshally** [Polymer/polymer-element-catalog#94]
Could a link to each elements github repo in https://github.com/PolymerElements be included under the action section near cart, demo, doc( shown in the left of the screenshot below)? I've heard this request in the Polymer Slack Channel and think it would help the community contribute to the project more efficiently.

![screen shot 2015-06-02 at 12 51 33 pm](https://cloud.githubusercontent.com/assets/3440317/7941567/2b863de6-0926-11e5-920c-fc112a95da5b.png)

**Comment by zacharytamas** [comment]
I support this. If not shown in this table for space, at least could be in the sidebar on an Element's page with the other actions. I'd like to be able to quickly jump to the code of an element if I want to take a closer look.

**Comment by zacharytamas** [comment]
@Bshally Could you add an `enhancement` label to this issue for triage purposes? Thanks.

**Comment by Bshally** [comment]
Looked through the github docs and they show how to do it, but it seems absent from my interface. I believe I cannot add a label to this issue as I am not listed as a contributor: [Stackoverflow](http://stackoverflow.com/questions/13829466/how-to-put-a-label-on-an-issue-in-github)

**Comment by zacharytamas** [comment]
Ah, yeah, I forgot about that. Sorry about that. I was just trying to help out the Polymer team :P

**Comment by tjsavage** [comment]
Appreciated! This is really good feedback, we'll look to add something like this.

**Comment by coreyfarrell** [comment]
This is especially important for some of the elements with very poor or completely absent documentation.  For example iron-flex-layout has "No Documentation Found".  A github link would allow people to easily look at the style provided by that element.

**Comment by ebidel** [comment]
+1. A lot of elements are missing docs and the only source of truth is Github atm.

**Comment by zacharytamas** [comment]
@ebidel Yeah I've noticed this too, which makes it even more frustrating when there's not an easy way to get to GitHub from there. Hopefully soon!

**Comment by mbleigh** [comment]
Add "Installation" section above "Documentation" in catalog view of iron-component-page that shows a link to the GitHub repo as well as an easily clickable way to add to collection and a bower install one-liner.
