### ISSUE TITLE
`paper-slider` documentation opens with a description of the `change` event instead of a description of the element

### ISSUE THREAD

**Issue by Ajedi32** [Polymer/polymer-element-catalog#95]
No idea if this problem is in the scope of this project, or another project entirely (given that this catalog sources it's data from multiple different locations), but currently the documentation for `paper-slider` has the wrong information listed in its introduction:

![paper slider polymer element catalog](https://cloud.githubusercontent.com/assets/1876931/7944080/36e254f6-092e-11e5-911f-9c17c27658b7.png)

This part which is currently listed at the top of the page is actually the documentation for the `changed` event, not a description of the element itself:

> Fired when the slider's value changes due to user interaction.
>
> Changes to the slider's value due to changes in an underlying bound variable will not trigger this event.

**Comment by tjsavage** [comment]
auto-moving this issue to Polymer/hydrolysis#119 and closing this one

**Comment by tjsavage** [comment]
Thanks @Ajedi32! This looks like polymer/hydrolysis seems to potentially be picking up the wrong comment block? Moved to that repo.

**Comment by Ajedi32** [comment]
Okay, thanks. I'll subscribe to that issue just in case any additional information is needed on my part.
