### ISSUE TITLE
`paper-input` demo unreachable from its documentation page

### ISSUE THREAD

**Issue by Ajedi32** [Polymer/polymer-element-catalog#96]
Currently when viewing the documentation for `paper-input`, there's no link to the demo page visible in the UI:

![paper textarea polymer element catalog](https://cloud.githubusercontent.com/assets/1876931/7944245/2ea4feaa-092f-11e5-9a06-734c9b259e36.png)

This happens despite the fact that there *is* actually a demo available for this element. You can get to it by viewing the documentation for a different element, viewing the demo for that element, then switching back to the docs for `paper-input` while the demo is still open, or by clicking the demo icon next to `paper-input` from the main catalog page:

![paper textarea demo polymer element catalog](https://cloud.githubusercontent.com/assets/1876931/7944290/5eb84bb0-092f-11e5-8d91-14847cbecdcd.png)

No idea if this is an issue with polymer-element-catalog, or just the result of polymer-element-catalog pulling in bad data from another project. Either way this should be fixed.

**Comment by Ajedi32** [comment]
`paper-behaviors` also exhibits this behavior.

**Comment by morethanreal** [comment]
I think this is the same as https://github.com/Polymer/polymer-element-catalog/issues/77

**Comment by Ajedi32** [comment]
From a user's perspective that seems like a completely different problem. I'm obviously not familiar with the code base of this project though, so I'll defer to you on whether that issue has the same underlying cause as this one.

**Comment by mbleigh** [comment]
Closed by 4f6b270a8
